import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Footer from "@/components/main/footer";
export default function MainLayout({ children }: { children: React.ReactNode }) {
  // "asdasdasd" yazısı artık SADECE ana layout'ta görünecek
  console.log("Main rendered");
  return (
    <>
        {children}
        <Footer />
    </>
  );
}
